version: 2

build:
  os: debian:bookworm
  tools:
    python: "3.10"


# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py


python:
  install:
    - method: pip
      path: .
